version: '3'
services:
    nginx:
        image: nginx
        ports:
            - 80:80
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ${PROJECT_ROOT}:/var/www/public
            - ./logs:/var/log/nginx
        links:
            - php
        depends_on:
            - php
        networks:
            - internal

    php:
        build: images/php
        links:
            - mysql
        volumes:
            - ${PROJECT_ROOT}:/var/www
            - ./images/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        command: ["composer install", "vendor/bin/doctrine orm:schema-tool:create"]
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
            CONTAINER_UID: ${UID}
        networks:
            - internal
    mysql:
        image: mariadb
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        networks:
            - internal

networks:
    internal:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.220.0/28
