version: '3'

services:
    php:
        build: images/php
        links:
            - postgres
        volumes:
            - ${PROJECT_ROOT}:/var/www
            - ./images/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./images/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
#        command: ["composer install", "vendor/bin/doctrine orm:schema-tool:create"]
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
            CONTAINER_UID: ${UID}
        networks:
            - internal

    postgres:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - ./postgres:/var/lib/postgres
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks:
            - internal

networks:
    internal:
        driver: bridge
